### ISSUE TITLE
redis server from the mslearn docs does not start up successfully 

### ISSUE THREAD

**Issue by TheKangaroo** [Azure-Samples/mslearn-aks-app-scaling-keda#1]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
I do not know if this is the right repo. This repo was linked in https://docs.microsoft.com/de-de/learn/modules/aks-app-scale-keda/5-exercise-deploy-app though the actuall issue is a step before in https://docs.microsoft.com/de-de/learn/modules/aks-app-scale-keda/4-concept-deploy-app. But there is no repo link to the image for the redis server.
Whenever I apply the deployment from the docs
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-microservice
spec:
  replicas: 10                     # Here we are telling K8S the number of pods to process the Redis list items
  selector:                         # Define the wrapping strategy
    matchLabels:                    # Match all pods with the defined labels
      app: contoso-microservice     # Labels follow the `name: value` template
  template:                         # This is the template of the pod inside the deployment
    metadata:
      labels:
        app: contoso-microservice
    spec:
      containers:
        - image: mcr.microsoft.com/mslearn/samples/redis-client:latest
          name: contoso-microservice

```
the redis servers does not start up.

### Any log messages given by the failure

Log messages of the pods:
```
2022-03-01T09:31:58.850Z	PANIC	workspace/main.go:39	dial tcp :0: connect: connection refused
main.main
	/workspace/main.go:39
runtime.main
	/usr/local/go/src/runtime/proc.go:225
panic: dial tcp :0: connect: connection refused

goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000a0180, 0x0, 0x0, 0x0)
	/go/pkg/mod/go.uber.org/zap@v1.16.0/zapcore/entry.go:234 +0x58d
go.uber.org/zap.(*SugaredLogger).log(0xc0002dfdd8, 0x766f04, 0x0, 0x0, 0xc0002dfdf8, 0x1, 0x1, 0x0, 0x0, 0x0)
	/go/pkg/mod/go.uber.org/zap@v1.16.0/sugar.go:234 +0xf6
go.uber.org/zap.(*SugaredLogger).Panic(...)
	/go/pkg/mod/go.uber.org/zap@v1.16.0/sugar.go:123
main.main()
	/workspace/main.go:39 +0x425
```

### Expected/desired behavior

redis runs successfully 

### OS and Version?

Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
happens on AKS and kind on intel and M1 MacOS.

### Versions

k8s 1.21.x

**Comment by TheKangaroo** [comment]
Sorry, I missed, that this is just a non-complete code snipped. Still it is kind of confusing.
The next page talks about "the Azure Cache for Redis we created earlier", but no azure cache for redis was mentioned before.

Anyway, I was just misunderstanding, the docs, so I'll close this issue.
Sorry for that :)
